- hosts: all
  become: true
  tasks:
    - name: Create temporary file for backup
      tempfile:
        state: file
        suffix: .tar.gz
      register: archive_temp

    - name: Get archive of Save folder
      archive:
        path: /home/stepmania/.stepmania-5.0/Save # todo: change to 5.1
        dest: "{{ archive_temp.path }}"
        format: gz

    - name: Download archived Save folder
      fetch:
        src: "{{ archive_temp.path }}"
        dest: "save-backups/{{ inventory_hostname }}-{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}.tar.gz"
        flat: yes

    - name: Remove temporary archive
      file:
        path: "{{ archive_temp.path }}"
        state: absent