- hosts: all
  become: true
  roles:
    - ssh
    - utils
    - lightdm
    - graphics
    - stepmania
    - analog-dance-pad
  tasks:
    - include_role:
        name: padmiss
      when: padmiss_api_key is defined