- hosts: all
  become: true
  tasks:
    - name: Copy firmware to machine
      copy:
        src: "{{ firmware }}"
        dest: /home/stepmania/.AnalogDancePad.hex
        owner: stepmania
        group: stepmania
        mode: "0644"

    - name: Stop analog-dance-pad service
      systemd:
        name: analog-dance-pad
        state: stopped

    - name: Run reset teensy script
      shell: npm run reset-teensy
      args:
        chdir: /opt/analog-dance-pad/server
      become_user: stepmania

    - name: Run teensy_loader_cli
      shell: /opt/teensy-loader-cli/teensy_loader_cli -v --mcu=atmega32u4 /home/stepmania/.AnalogDancePad.hex

    - name: Run teensy_loader_cli again for another pad ":D"
      shell: /opt/teensy-loader-cli/teensy_loader_cli -v --mcu=atmega32u4 /home/stepmania/.AnalogDancePad.hex

    - name: Start analog-dance-pad service
      systemd:
        name: analog-dance-pad
        state: started
