- name: Give permissions to everyone for USB reader devices
  copy:
    content: 'SUBSYSTEM=="usb", ATTR{idVendor}=="08ff", ATTR{idProduct}=="0009", MODE="0666"'
    dest: /etc/udev/rules.d/99-permissions-to-rfid-reader.rules
  register: udev

- name: Reload udev permissions
  shell: udevadm control --reload
  when: udev.changed

- name: Install python3, python3.7-venv and python3-venv (dunno why we need the last one, but we do)
  apt:
    name: python3.7,python3.7-venv,python3-venv

- name: Fetch padmiss-daemon source
  git:
    repo: https://github.com/electromuis/padmiss-daemon
    dest: /opt/padmiss-daemon
    version: 326c3817b4296ed3d02e5b5ba602637efb07990b
  notify: restart padmiss-daemon
  diff: no

- name: Install padmiss-daemon requirements
  pip:
    requirements: /opt/padmiss-daemon/requirements.txt
    virtualenv: /home/stepmania/.padmiss-daemon-venv
    virtualenv_command: '/usr/bin/python3.7 -m venv'

- name: Create profile folder
  file:
    path: /opt/padmiss-daemon-profile
    state: directory
    owner: stepmania
    group: stepmania

- name: Create backup folder
  file:
    path: /opt/padmiss-daemon-backups
    state: directory
    owner: stepmania
    group: stepmania

- name: Create Padmiss folder inside Stepmania save
  file:
    path: /home/stepmania/.stepmania-5.0/Save/Padmiss
    state: directory
    owner: stepmania
    group: stepmania

- name: Create configuration folder
  file:
    path: /home/stepmania/.padmiss
    state: directory
    owner: stepmania
    group: stepmania

- name: Copy configuration file
  template:
    src: templates/config.json.template
    dest: /home/stepmania/.padmiss/config.json
  notify: restart padmiss-daemon

- name: Create padmiss-daemon service
  copy:
    src: files/padmiss-daemon.service
    dest: /etc/systemd/system/padmiss-daemon.service
  notify: restart padmiss-daemon

- name: Enable padmiss-daemon service
  systemd:
    name: padmiss-daemon
    state: started
    daemon_reload: yes
    enabled: yes
